r"""
Hyperoctahedral species

This module provides the internal infrastructure for *polynomial
`r`-species* in the sense of Henderson [Henderson2004]_, i.e. functors
on the category `\mathbf B_r` of finite sets with a free action of the
cyclic group `C_r` of order `r`.  The case `r = 2` is the
*hyperoctahedral* case.

The present module only contains the combinatorial model of the
canonical permutation representation of the wreath product

.. MATH::

    W(r,n) = C_r \wr S_n \leq S_{rn},

together with the computation of the cycle type of its elements.  The
species themselves are built on top of this in
:mod:`sage.rings.species_hyperoctahedral`.

The group `W(r,n)` is realized as a permutation group on the `r n`
points `1, \ldots, r n`, split into `n` *consecutive* blocks of size
`r`.  This block system is the data that distinguishes `W(r,n)`-sets
from ordinary `S_{rn}`-sets; it is therefore available at all times
through :func:`_wreath_blocks`.

Following Henderson, conjugacy classes of `W(r,n)` are indexed by
collections `(a_i(\zeta))_{i \geq 1, \zeta \in \mu_r}` of
nonnegative integers with

.. MATH::

    \sum_{i \geq 1} \sum_{\zeta \in \mu_r} i a_i(\zeta) = n,

where `a_i(\zeta)` counts the cycles of length `i` and type `\zeta`.
We never represent `\zeta` by an actual root of unity: instead the
`r` possible types are the labels `0, 1, \ldots, r-1` and the type of a
cycle is the sum, modulo `r`, of the sign labels occurring in it.
:func:`_wreath_cycle_type` returns this data as an `r`-tuple of
(ordinary) partitions of `n`.

The conjugacy classes of *subgroups* of `W(r,n)`, which are needed to
classify molecular `r`-species, are available directly from the
permutation group returned by :func:`_wreath_group`, via
:meth:`~sage.groups.perm_gps.permgroup.PermutationGroup_generic.conjugacy_classes_subgroups`::

    sage: from sage.groups.perm_gps.hyperoctahedral_group import _wreath_group
    sage: G = _wreath_group(2, 2)
    sage: len(G.conjugacy_classes_subgroups())
    8

.. NOTE::

    The groups in :mod:`sage.combinat.colored_permutations` realize the
    same abstract wreath products, but the permutation realization used
    by
    :meth:`~sage.combinat.colored_permutations.ColoredPermutations.as_permutation_group`
    labels the `r n` points differently and does not expose a block
    system.  The consecutive-block model used here is the one required
    for `r`-species, so we build the permutation group directly.

REFERENCES:

.. [Henderson2004] Anthony Henderson.
   *Representations of wreath products on cohomology of De Concini-Procesi
   compactifications*.
   International Mathematics Research Notices 2004, no. 20, 981-1021.

AUTHORS:

- Martin Rubey (2025): initial version
"""


# ****************************************************************************
#       Copyright (C) 2025 Martin Rubey <martin.rubey@tuwien.ac.at>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#                  https://www.gnu.org/licenses/
# ****************************************************************************

from sage.combinat.partition import Partition
from sage.groups.perm_gps.permgroup import PermutationGroup
from sage.misc.cachefunc import cached_function
from sage.rings.integer_ring import ZZ


@cached_function
def _wreath_group(r, n):
    r"""
    Return the canonical permutation representation of `W(r,n) = C_r \wr S_n`.

    The `r n` points are split into `n` consecutive blocks of size `r`,
    and the group is generated by the cyclic rotation of each block and
    the simultaneous swap of two adjacent blocks.

    INPUT:

    - ``r`` -- positive integer; the order of the cyclic group
    - ``n`` -- nonnegative integer

    OUTPUT:

    The permutation group `C_r \wr S_n` acting on `\{1, \ldots, r n\}`.

    EXAMPLES:

    The hyperoctahedral group `W(2,2)` has order `2^2 2! = 8`::

        sage: from sage.groups.perm_gps.hyperoctahedral_group import _wreath_group
        sage: G = _wreath_group(2, 2)
        sage: G.order()
        8
        sage: G.order() == 2**2 * factorial(2)
        True

    `W(2,1)` is the cyclic group of order two::

        sage: G = _wreath_group(2, 1)
        sage: G.order()
        2
        sage: G.is_cyclic()
        True

    For `r = 1` we recover the symmetric group::

        sage: all(_wreath_group(1, n) == SymmetricGroup(n) for n in range(6))
        True

    In general `|W(r,n)| = r^n n!`::

        sage: all(_wreath_group(r, n).order() == r**n * factorial(n)
        ....:     for r in range(1, 5) for n in range(5))
        True

    For `n = 0` we get the trivial group on the empty set::

        sage: _wreath_group(3, 0).order()
        1
        sage: _wreath_group(3, 0).degree()
        0

    The block system is respected::

        sage: G = _wreath_group(2, 2)
        sage: from sage.groups.perm_gps.hyperoctahedral_group import _wreath_blocks
        sage: all(tuple(sorted(g(x) for x in b)) in _wreath_blocks(2, 2)
        ....:     for g in G.gens() for b in _wreath_blocks(2, 2))
        True

    TESTS::

        sage: _wreath_group(0, 2)
        Traceback (most recent call last):
        ...
        ValueError: r must be a positive integer
        sage: _wreath_group(2, -1)
        Traceback (most recent call last):
        ...
        ValueError: n must be a nonnegative integer
    """
    r = ZZ(r)
    n = ZZ(n)
    if r < 1:
        raise ValueError("r must be a positive integer")
    if n < 0:
        raise ValueError("n must be a nonnegative integer")

    # The cyclic rotation of each of the n blocks.
    gens = [tuple(range(i * r + 1, i * r + r + 1)) for i in range(n)]
    # The simultaneous swap of two adjacent blocks.
    gens += [tuple((i * r + t + 1, (i + 1) * r + t + 1) for t in range(r))
             for i in range(n - 1)]
    return PermutationGroup(gens, domain=range(1, r * n + 1))


def _wreath_blocks(r, n):
    r"""
    Return the block system of the canonical representation of `W(r,n)`.

    The blocks are the `n` consecutive subsets of size `r` of
    `\{1, \ldots, r n\}`.

    INPUT:

    - ``r`` -- positive integer; the order of the cyclic group
    - ``n`` -- nonnegative integer

    OUTPUT:

    A tuple of `n` tuples, the `i`-th entry being the `i`-th block.

    EXAMPLES::

        sage: from sage.groups.perm_gps.hyperoctahedral_group import _wreath_blocks
        sage: _wreath_blocks(2, 3)
        ((1, 2), (3, 4), (5, 6))
        sage: _wreath_blocks(3, 2)
        ((1, 2, 3), (4, 5, 6))
        sage: _wreath_blocks(4, 1)
        ((1, 2, 3, 4),)

    The block system of `W(r,0)` is empty::

        sage: _wreath_blocks(2, 0)
        ()
    """
    r = ZZ(r)
    n = ZZ(n)
    return tuple(tuple(range(i * r + 1, i * r + r + 1)) for i in range(n))


def _wreath_cycle_type(g, r):
    r"""
    Return the cycle type of ``g`` in `W(r,n)`.

    The cycle type is returned as the `r`-tuple of partitions
    `(\lambda^{(0)}, \ldots, \lambda^{(r-1)})`, where
    `\lambda^{(j)}` records the lengths of the cycles of type `j`.

    Here the *type* of a cycle is the sum, modulo `r`, of the sign
    labels of its elements; this is the cycle type used by Henderson
    [Henderson2004]_, cf. [Henderson2004]_, (1.1).

    INPUT:

    - ``g`` -- an element of :func:`_wreath_group` for some `n`
    - ``r`` -- positive integer; the order of the cyclic group

    EXAMPLES:

    A single block swap::

        sage: from sage.groups.perm_gps.hyperoctahedral_group import (_wreath_group,
        ....:     _wreath_cycle_type)
        sage: G = _wreath_group(2, 3)
        sage: _wreath_cycle_type(G([3, 4, 1, 2, 5, 6]), 2)
        ([2, 1], [])

    Flipping every sign::

        sage: _wreath_cycle_type(G([2, 1, 4, 3, 6, 5]), 2)
        ([], [1, 1, 1])

    A `3`-cycle with trivial signs::

        sage: _wreath_cycle_type(G([(1, 3, 5), (2, 4, 6)]), 2)
        ([3], [])

    A `3`-cycle of nontrivial type::

        sage: g = G([(1, 2)]) * G([(1, 3, 5), (2, 4, 6)])
        sage: _wreath_cycle_type(g, 2)
        ([], [3])

    For `r = 1` this is the ordinary cycle type::

        sage: S = _wreath_group(1, 4)
        sage: _wreath_cycle_type(S([2, 1, 4, 3]), 1)
        ([2, 2],)

    Conjugate elements have the same cycle type::

        sage: g = G([3, 4, 1, 2, 5, 6])
        sage: k = G([(1, 2)])
        sage: _wreath_cycle_type(g, 2) == _wreath_cycle_type(k * g * k, 2)
        True

    Conversely, for `r = 2` and `n \leq 3`, elements with the same
    cycle type are conjugate in `W(r,n)`::

        sage: from collections import defaultdict
        sage: for r, n in [(2, 1), (2, 2), (2, 3)]:
        ....:     G = _wreath_group(r, n)
        ....:     by_type = defaultdict(list)
        ....:     for g in G:
        ....:         by_type[_wreath_cycle_type(g, r)].append(g)
        ....:     assert len(by_type) == len(G.conjugacy_classes())
        ....:     for elts in by_type.values():
        ....:         assert all(G.are_conjugate(elts[0], h) for h in elts)

    TESTS::

        sage: _wreath_cycle_type(G([1, 2, 3, 4, 5, 6]), 4)
        Traceback (most recent call last):
        ...
        ValueError: 6 is not divisible by r = 4
    """
    r = ZZ(r)
    if r < 1:
        raise ValueError("r must be a positive integer")
    degree = g.parent().degree()
    if degree % r:
        raise ValueError(f"{degree} is not divisible by r = {r}")
    n = degree // r

    # Extract the underlying permutation of blocks and the sign labels.
    sigma = []
    signs = []
    for i in range(n):
        image = g(i * r + 1)
        sigma.append((image - 1) // r + 1)
        signs.append((image - 1) % r)

    # For each cycle of the block permutation, add its length to the
    # partition indexed by the sum of its sign labels (modulo r).
    types = [[] for _ in range(r)]
    seen = [False] * n
    for start in range(n):
        if seen[start]:
            continue
        current = start
        length = 0
        typ = 0
        while not seen[current]:
            seen[current] = True
            length += 1
            typ = (typ + signs[current]) % r
            current = sigma[current] - 1
        types[typ].append(length)

    return tuple(Partition(sorted(parts, reverse=True)) for parts in types)


def _hyperoctahedral_disjoint_direct_product_decomposition(H, r):
    r"""
    Return the `r`-species disjoint direct product decomposition of ``H``.

    For a subgroup `H \leq W(r,n)`, every component of the ordinary
    disjoint direct product decomposition of Chang--Jefferson is a union
    of complete `C_r`-blocks, except that pointwise-fixed `C_r`-blocks
    are represented as `r` singleton fixed points.  This function
    bundles each such group of singletons into its `C_r`-block, so that
    the result is the decomposition of `H` as a direct product of
    `r`-species.

    INPUT:

    - ``H`` -- a permutation group whose domain is a union of complete
      `C_r`-blocks; typically `H` is the restriction of a subgroup of
      `W(r,n)` to such a union
    - ``r`` -- positive integer; the order of the cyclic group

    OUTPUT:

    A :class:`~sage.combinat.set_partition.SetPartition` of the domain
    of ``H``, each part being a union of complete `C_r`-blocks.

    EXAMPLES:

    The trivial subgroup of `W(2,2)` is the product of two trivial
    degree-one `r`-species::

        sage: from sage.groups.perm_gps.hyperoctahedral_group import (
        ....:     _wreath_group, _hyperoctahedral_disjoint_direct_product_decomposition)
        sage: H = _wreath_group(2, 2).subgroup([])
        sage: _hyperoctahedral_disjoint_direct_product_decomposition(H, 2)
        {{1, 2}, {3, 4}}

    The same subgroup of `W(1,4)` reduces to the ordinary decomposition::

        sage: H = _wreath_group(1, 4).subgroup([])
        sage: _hyperoctahedral_disjoint_direct_product_decomposition(H, 1)
        {{1}, {2}, {3}, {4}}
        sage: (H.disjoint_direct_product_decomposition()
        ....:  == _hyperoctahedral_disjoint_direct_product_decomposition(H, 1))
        True

    A subgroup acting nontrivially on a block is kept as is::

        sage: G = _wreath_group(2, 2)
        sage: H = G.subgroup([(3, 4)])
        sage: _hyperoctahedral_disjoint_direct_product_decomposition(H, 2)
        {{1, 2}, {3, 4}}

    TESTS:

    No component of the result is a genuine non-block-compatible
    component::

        sage: from sage.groups.perm_gps.hyperoctahedral_group import _wreath_blocks
        sage: G = _wreath_group(2, 3)
        sage: for H in G.conjugacy_classes_subgroups():
        ....:     dec = _hyperoctahedral_disjoint_direct_product_decomposition(H, 2)
        ....:     for comp in dec:
        ....:         for b in _wreath_blocks(2, 3):
        ....:             assert set(b).isdisjoint(comp) or set(b).issubset(comp)

        sage: _hyperoctahedral_disjoint_direct_product_decomposition(_wreath_group(3, 1), 2)
        Traceback (most recent call last):
        ...
        ValueError: 3 is not divisible by r = 2
    """
    from sage.combinat.set_partition import SetPartition
    r = ZZ(r)
    if r < 1:
        raise ValueError("r must be a positive integer")
    degree = H.degree()
    if degree % r:
        raise ValueError(f"{degree} is not divisible by r = {r}")

    decomposition = H.disjoint_direct_product_decomposition()
    blocks = _wreath_blocks(r, degree // r)

    # the points that occur as singleton components
    singletons = set()
    for part in decomposition:
        if len(part) == 1:
            singletons.update(part)

    # bundle the singleton components belonging to a fixed block
    result = [frozenset(block) for block in blocks
              if set(block).issubset(singletons)]
    # keep the genuine (nontrivial) components
    result.extend(frozenset(part) for part in decomposition if len(part) > 1)
    return SetPartition(result)
